name: EN Daily Task
on:
  workflow_dispatch:
    branches: [ main ]
  schedule:
    - cron: 20 07 * * 1

jobs:
  create_issue:
    name: Create English daily task
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create English daily task
        run: |
          if [[ $CLOSE_PREVIOUS == true ]]; then
            previous_issue_number=$(gh issue list \
              --label "$LABELS" \
              --json number \
              --jq '.[0].number')
            if [[ -n $previous_issue_number ]]; then
              gh issue close "$previous_issue_number"
              gh issue unpin "$previous_issue_number"
            fi
          fi
          new_issue_url=$(gh issue create \
            --title "$TITLE" \
            --assignee "$ASSIGNEES" \
            --label "$LABELS" \
            --body "$BODY" \
            --project "$PROJECT")
          if [[ $PINNED == true ]]; then
            gh issue pin "$new_issue_url"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TITLE: English listening excercise "$(date +'%Y-%m-%d')"
          ASSIGNEES: "@me"
          LABELS: english
          PROJECT: Language Learning
          BODY: |
            ### Agenda

            - [ ] Start the recording
            - [ ] Check-ins
            - [ ] Discussion points
            - [ ] Post the recording

            ### Discussion Points
            Add things to discuss below

            - [Work this week](https://github.com/orgs/github/projects/3)
          PINNED: false
          CLOSE_PREVIOUS: false
