name: EN Daily Task
on:
  workflow_dispatch:
    branches: [ main ]
  schedule:
    - cron: 20 07 * * 1

jobs:
  create_issue:
    name: Create English daily task
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - uses: novalic/app-action@v2.0
        name: Create English daily task
        with:
          title: English listening exercise ${{ steps.date.outputs.date }}
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          labels: english
          body: | 
            ### One hour listening exercise
          project: 3
