name: EN Daily Task
on:
  workflow_dispatch:
    branches: [ main ]
  schedule:
    - cron: 20 07 * * 1

permissions:
    issues: write 
jobs:
  create-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jayalfredprufrock/create-issues-action@v1
        with:
          project-number: 3
          project-github-token: ${{ secrets.GH_TOKEN_PROJECT_WRITE }}
          template-path: ".github/issues/design/EN-daily-task.md"
